### PR TITLE
Add Rails 5.0.1 support

### PR DESCRIPTION
**Pull request by Alfarlost**

### CODE REVIEW

**Comment by pelletencate** [comment]
Could you please get this one merged?

**Comment by kieranklaassen** [comment]
Please merge!! thanks

**Comment by pachun** [comment]
Merge would be sweet! Thanks!

**Comment by wild5r** [comment]
thanks for fixes

**Comment by KapilMetacube** [comment]
Still encountering issue even after this is merged
```
    activeadmin (~> 1.1) was resolved to 1.1.0, which depends on
      railties (< 5.2, >= 4.2)

    activeadmin_hstore_editor (~> 0.0.5) was resolved to 0.0.5, which depends on
      railties (< 5.0, >= 3.0)
```

Rubygems.org is still showing different dependency versions (old ones).

**Pull request merged**
